### ISSUE TITLE
[ENH] Provide example data in the dashboard to try out

### ISSUE THREAD

**Issue by surchs** [neurobagel/proc_dash#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

As a curious user who doesn't know about mr_proc or any of these great things, I'd like to have the option to populate the dashboard with example data when I first try it out, so that I can get started playing around with it immediately, without having to first ask someone for data - or do some other strenuous preparation.

- [x] add button to navigate to a "Sample input file" that they can download (`example_bagel.csv`)
- [x] add to README instructions for obtaining sample data

**Comment by alyssadai** [comment]
Aha, good question! I do have an example small correctly-formatted bagel.csv in https://github.com/neurobagel/proc_dash/blob/main/tests/data/example_bagel.csv which I use for testing, and a first-time user could download to use to play around with the dashboard as well.

Can definitely add more clear "Try it out" instructions in the README as part of issue https://github.com/neurobagel/proc_dash/issues/45. Is this along the lines of what you're looking for? Or were you envisioning something like an actual "Try with example data" button in the dashboard that, when clicked, would auto-populate the rest of the components?

**Comment by surchs** [comment]
Oh, entirely up to you. I just always assume that people have very short attention spans so when they load a tool and can't use it without reading how to use it first, I expect them to move on. So a button to "try out with this data" could help. Or a link to "if you don't have data, get some example data from here" with a link. Essentially anything that lets someone start playing with the tool after navigating to it via the URL

**Comment by alyssadai** [comment]
Good point! I like the idea of having a direct link to some example data in the app - will include that in addition to the README instructions. 🙂
